from typing import Union, Protocol, TYPE_CHECKING
from pygame import Surface

from core.scene.EventState import EventState
if TYPE_CHECKING: # Prevent exception of circular import
    from core.scene.SceneManager import SceneManager


class Scene(Protocol):
    def __init__(self, scene_manager: "SceneManager", *, is_overlay: bool = False, is_exclusive: bool = False): ...
    def enter(self) -> None: ...
    def leave(self) -> None: ...
    def handle(self, ev: EventState) -> None: ...
    def update(self, dt: float) -> None: ...
    def draw(self, surface: Surface) -> None: ...
    def scale(self, base_value: Union[int, float]) -> float: ...
    def rscale(self, base_value: Union[int, float]) -> int: ...
    def reload_language_data(self) -> None: ...
